#!/usr/bin/env python3
"""Export the fitted low-rank radiation equation as quantized C constants."""

from pathlib import Path

import numpy as np


ROOT = Path(__file__).resolve().parents[1]
data = np.load(ROOT / "reports/high-resolution-radiation-fit.npz")
spatial = data["spatial"]
spectral = data["spectral"]
rank = int(data["rank"])
spatial_terms = spatial.shape[0]
spectral_terms = spectral.shape[0]

quantized_spatial = np.zeros_like(spatial, dtype=np.int16)
quantized_spectral = np.zeros_like(spectral, dtype=np.int16)
scales = []
for component in range(rank):
    spatial_scale = max(np.max(np.abs(spatial[:, component])) / 32760, 1e-18)
    spectral_scale = max(np.max(np.abs(spectral[:, component])) / 32760, 1e-18)
    quantized_spatial[:, component] = np.round(
        spatial[:, component] / spatial_scale
    ).astype(np.int16)
    quantized_spectral[:, component] = np.round(
        spectral[:, component] / spectral_scale
    ).astype(np.int16)
    scales.append(spatial_scale * spectral_scale)


def array_rows(name, values):
    rows = [f"static const int16_t {name}[{values.shape[0]}][{values.shape[1]}] = {{"]
    rows.extend(" {" + ",".join(str(int(value)) for value in row) + "}," for row in values)
    rows.append("};")
    return rows


lines = [
    "/* Generated by export-high-resolution-radiation.py from all 480 exact recordings. */",
    f"#define HIGHRES_RANK {rank}",
    f"#define HIGHRES_SPATIAL_TERMS {spatial_terms}",
    f"#define HIGHRES_SPECTRAL_TERMS {spectral_terms}",
    *array_rows("highres_spatial", quantized_spatial),
    *array_rows("highres_spectral", quantized_spectral),
    "static const double highres_scale[HIGHRES_RANK] = {" +
    ",".join(f"{value:.17g}" for value in scales) + "};",
    "",
]
(ROOT / "tools/high-resolution-radiation-fit.h").write_text("\n".join(lines))
print(
    f"wrote tools/high-resolution-radiation-fit.h: rank={rank}, "
    f"{spatial_terms * rank + spectral_terms * rank} int16 coefficients"
)
