#!/usr/bin/env python3
"""Fit/export a global log-frequency equation from the development calibration.

The NPZ stores the legacy 14-band calibration, not runtime data. Its old Hermite
response is sampled densely here only, to preserve the existing voicing while
replacing interval interpolation with a least-squares Chebyshev polynomial.
"""
import argparse
from pathlib import Path

import numpy as np
from numpy.polynomial.chebyshev import chebfit
from scipy.interpolate import CubicHermiteSpline

ROOT = Path(__file__).resolve().parents[1]
EDGES = np.array([20, 40, 63, 100, 160, 250, 400, 630, 1000, 1600,
                  2500, 4000, 6300, 10000, 16000])
POSITIONS = np.log2(np.sqrt(EDGES[:-1] * EDGES[1:]) / 27.5)
MID = (POSITIONS[0] + POSITIONS[-1]) / 2
HALF = (POSITIONS[-1] - POSITIONS[0]) / 2
DEGREE = 64
LIMIT_WIDTH = .0005  # octaves; smooth constant continuation beyond calibration


def quantize(values):
    scales = np.maximum(np.max(np.abs(values), axis=0) / 32760, 1e-30)
    return np.rint(values / scales).astype(np.int16), scales


def legacy_calibration():
    """Reconstruct the exact quantized model shipped before the curve change."""
    data = np.load(ROOT / "reports/high-resolution-radiation-fit.npz")
    assert int(data["pitch_degree"]) == 14 and int(data["velocity_degree"]) == 7
    spatial, spatial_scale = quantize(data["spatial"])
    spectral, spectral_scale = quantize(data["spectral"])
    spectral = spectral * (spatial_scale * spectral_scale)
    slopes = np.vstack((
        (spectral[1] - spectral[0]) / (POSITIONS[1] - POSITIONS[0]),
        (spectral[2:] - spectral[:-2]) / (POSITIONS[2:] - POSITIONS[:-2])[:, None],
        (spectral[-1] - spectral[-2]) / (POSITIONS[-1] - POSITIONS[-2]),
    ))
    return spatial, CubicHermiteSpline(POSITIONS, spectral, slopes)


def fitted_calibration():
    spatial, legacy = legacy_calibration()
    # More fitting observations than coefficients; no polynomial interpolation
    # through the original bands. Cosine spacing conditions the global fit.
    x = np.cos(np.pi * (np.arange(4096) + .5) / 4096)
    coefficients = chebfit(x, legacy(MID + HALF * x), DEGREE)
    spectral, scales = quantize(coefficients)
    return spatial, spectral, scales


def array_rows(name, values):
    return [f"static const int16_t {name}[{values.shape[0]}][{values.shape[1]}] = {{",
            *(" {" + ",".join(str(int(value)) for value in row) + "}," for row in values),
            "};"]


def header_text():
    spatial, spectral, scales = fitted_calibration()
    return "\n".join([
        "/* Generated by export-high-resolution-radiation.py. Global Chebyshev coefficients,",
        " * not sampled band values. Calibration provenance: the 480-recording fit. */",
        "#ifndef HIGH_RESOLUTION_RADIATION_FIT_H",
        "#define HIGH_RESOLUTION_RADIATION_FIT_H",
        '#include <stdint.h>',
        '#include "continuous-piano-curves.h"',
        f"#define HIGHRES_RANK {spatial.shape[1]}",
        f"#define HIGHRES_SPATIAL_TERMS {spatial.shape[0]}",
        f"#define HIGHRES_SPECTRAL_TERMS {spectral.shape[0]}",
        *array_rows("highres_spatial", spatial),
        *array_rows("highres_spectral", spectral),
        "static const double highres_scale[HIGHRES_RANK] = {" +
        ",".join(f"{value:.17g}" for value in scales) + "};",
        "static inline double highres_frequency_coordinate(double frequency) {",
        f" double octave = piano_smooth_limit(log2(frequency / 27.5), {POSITIONS[0]:.17g}, {POSITIONS[-1]:.17g}, {LIMIT_WIDTH});",
        f" return (octave - {MID:.17g}) / {HALF:.17g};",
        "}",
        "#endif",
        "",
    ])


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    path = ROOT / "tools/high-resolution-radiation-fit.h"
    generated = header_text()
    if args.check:
        if path.read_text() != generated:
            raise SystemExit("radiation header differs; run tools/export-high-resolution-radiation.py")
        print("Global radiation coefficients match the reproducible fit.")
    else:
        path.write_text(generated)
        print(f"Wrote global degree-{DEGREE} radiation fit to {path.relative_to(ROOT)}")
