#include <math.h>
#include <stdint.h>
#include <string.h>
#include <wasm_simd128.h>

#define SAMPLE_RATE 44100
#define MAX_SAMPLES 1323000
#define MAX_MODES 384
#define IMPACT_COUNT 22
#define MAX_FORCE 150
#define SOUND_FILTER_COUNT 10
#define NOISE_FILTER_COUNT 14
#define FORCE_O 0
#define SOUND_O MAX_FORCE
#define NOISE_O (SOUND_O + SOUND_FILTER_COUNT * 4)
#define BOARD_O (NOISE_O + NOISE_FILTER_COUNT * 4)
#define RAD_O BOARD_O
#define PI 3.14159265358979323846264338327950288
#define TWO_PI (2 * PI)

typedef struct { double x, y; } Point;

static float output[MAX_SAMPLES];
static unsigned char calibration[1845];
static double state[BOARD_O + 8];
static double modes[19][MAX_MODES];
static uint8_t mode_delays[2][MAX_MODES];
static uint32_t mode_cutoff[MAX_MODES];
static double impact_state[17][IMPACT_COUNT];
static double soundboard_filters[SOUND_FILTER_COUNT][10];
static double noise_filters[NOISE_FILTER_COUNT][9];
static int filters_ready;
static int impact_body_count;
static int impact_attack_count;

static const Point stiffness_curve[] = {{21, 2.9e-4}, {24, 2.3e-4}, {27, 2.45e-4}, {30, 8.3e-5}, {33, 8.2e-5}, {36, 1.34e-4}, {39, 2.5e-4}, {42, 1.6e-4}, {45, 1.4e-4}, {48, 1.05e-4}, {51, 1.25e-4}, {54, 1.82e-4}, {57, 2.12e-4}, {60, 2.95e-4}, {63, 3.5e-4}, {66, 5.35e-4}, {69, 6.2e-4}, {72, 8.3e-4}, {75, 1.04e-3}, {78, 1.1e-3}, {81, 1.73e-3}, {84, 2.18e-3}, {87, 3.04e-3}, {93, 5.4e-3}, {108, 9e-3}};
static const Point radiation_curve_db[] = {{21, -0.24}, {24, 0.69}, {27, 0.25}, {30, -3.5}, {33, -2.2}, {36, -3.33}, {39, 0.43}, {42, 0.71}, {45, -0.9}, {48, -1.98}, {51, -1.27}, {54, -3.88}, {57, -5.42}, {60, -2.09}, {63, -6.99}, {66, -3.79}, {69, -3.22}, {72, -1.59}, {75, 1.2}, {78, 3.24}, {81, 0.1}, {84, 2.35}, {87, 6.72}, {90, 3.84}, {93, 7.01}, {96, 4.63}, {99, 2.42}, {102, 6.17}, {105, 2.38}, {108, 4.39}};
static const Point bridge_curve_db[] = {{27.5, -2}, {55, -4}, {70, 0}, {100, 1}, {200, 0}, {250, -1.5}, {500, -1.5}, {800, -2.5}, {1200, -1.5}, {1800, -1.5}, {2400, 1}, {3200, 3}, {4500, 3}, {6000, 1.5}, {8000, 2}, {16000, 0}};
static const double modal_radiation_db[3][16] = {{-2, 4.1, -0.6, -3.9, -2.9, -1.4, 1.2, -7.3, -2.8, -1.2, -3.7, -7, -4.1, -4.6, -5.6, -8}, {2.3, -2.7, -5.2, -4.2, -3.1, -1.8, 6.3, 6.2, 1.4, -0.7, -1.6, -0.6, 0.6, -0.3, 1, 0}, {0, -10.5, 7, 2.5, -4.4, -3.6, -4.9, -3.6, -3.1, -2.8, -1.7, -1.7, 0, 0, 0, 0}};
static const double mobility_band_edges[] = {40, 63, 100, 160, 250, 400, 630, 1000, 1600, 2500, 4000, 6300, 10000, 16000};
static const double bridge_loss_frequencies[] = {200, 800, 2500, 6500};
static const double impact_modes[IMPACT_COUNT][3] = {{58, .035, .065}, {87, .031, -.058}, {126, .028, .052}, {181, .025, -.046}, {255, .023, .041}, {354, .021, -.036}, {486, .019, .032}, {661, .018, -.028}, {891, .017, .025}, {1188, .016, -.022}, {1565, .015, .019}, {2036, .0085, -.25}, {2617, .008, .35}, {3323, .012, -.07}, {4168, .011, .0115}, {5164, .01, -.01}, {6321, .0092, .0087}, {7648, .0085, -.0075}, {9151, .0081, .0096}, {10834, .0075, -.0081}, {12696, .0069, .00675}, {14735, .00625, -.00555}};
static const double soundboard_specs[SOUND_FILTER_COUNT][3] = {{72, 1.25, .16}, {116, 1.6, .2}, {185, 1.8, .19}, {285, 2.1, .16}, {435, 2.4, .13}, {690, 2.7, .1}, {1080, 3.1, .075}, {1720, 3.5, .052}, {2750, 4, .034}, {4300, 4.4, .018}};
static const double noise_cutoffs[NOISE_FILTER_COUNT] = {6500, 6500, 6500, -1800, -7500, 15500, 1100, 1100, -180, 630, 630, -55, -1600, 8000};

static inline double clamp(double value, double minimum, double maximum) { return fmin(maximum, fmax(minimum, value)); }
static inline double lerp(double a, double b, double amount) { return a + (b - a) * amount; }
static inline double smoothstep(double value) { return value * value * (3 - 2 * value); }
static inline double transition(double value) { return smoothstep(clamp(value, 0, 1)); }
static inline double bell(double value, double center, double width, double power) { return exp(-pow((value - center) / width, power)); }
static inline double decay(double sample, double seconds) { return exp(-sample / (seconds * SAMPLE_RATE)); }
static inline uint32_t decay_samples(double amplitude, double pole) { return amplitude > 1e-6 ? (uint32_t)ceil(log(1e-6 / amplitude) / log(pole)) : 0; }

static double interpolate_curve(double value, const Point *anchors, int count, int flags) {
 for (int index = 1; index < count; index += 1) { Point upper = anchors[index], lower = anchors[index - 1]; if (value <= upper.x) { double position = clamp(flags & 1 ? log(value / lower.x) / log(upper.x / lower.x) : (value - lower.x) / (upper.x - lower.x), 0, 1); if (flags & 2) position = smoothstep(position); return flags & 4 ? exp(lerp(log(lower.y), log(upper.y), position)) : lerp(lower.y, upper.y, position); } }
 return anchors[count - 1].y;
}

static inline double signed_byte(const unsigned char *bytes, int index, double scale) { int byte = bytes[index]; return (byte > 127 ? byte - 256 : byte) * scale; }

static double calibration_value(const unsigned char *bytes, int columns, double midi, double velocity, int column, double scale, double middle_velocity) {
 double pitch_position = clamp((midi - 23) / 6, 0, 14); int pitch_index = fmin(13, floor(pitch_position)); double pitch_blend = transition(pitch_position - pitch_index); int velocity_index = velocity < middle_velocity ? 0 : 1; double velocity_blend = clamp(velocity_index == 0 ? (velocity - .106) / (middle_velocity - .106) : (velocity - middle_velocity) / (.976 - middle_velocity), 0, 1); int lower = (pitch_index * 3 + velocity_index) * columns + column, upper = lower + columns * 3; double lower_low = signed_byte(bytes, lower, scale), lower_high = signed_byte(bytes, lower + columns, scale), upper_low = signed_byte(bytes, upper, scale), upper_high = signed_byte(bytes, upper + columns, scale); return lerp(lerp(lower_low, lower_high, velocity_blend), lerp(upper_low, upper_high, velocity_blend), pitch_blend);
}

static inline double radiation_eq_db(double midi, double velocity, int band) { return calibration_value(calibration + 1350, 3, midi, velocity, band, .25, .476); }

static double bridge_loss_db_per_second(double midi, double velocity, double frequency) {
 int index = 0; while (index < 2 && frequency > bridge_loss_frequencies[index + 1]) index += 1; double blend = clamp(log(frequency / bridge_loss_frequencies[index]) / log(bridge_loss_frequencies[index + 1] / bridge_loss_frequencies[index]), 0, 1); double lower = calibration_value(calibration + 1485, 4, midi, velocity, index, .25, .541), upper = calibration_value(calibration + 1485, 4, midi, velocity, index + 1, .25, .541); return lerp(lower, upper, blend);
}

static inline double board_loss_db_per_second(double midi, double velocity, int band) { return calibration_value(calibration + 1665, 4, midi, velocity, band, .25, .541); }

static double modal_radiation_gain(int partial, double bass_to_middle, double middle_to_treble, double velocity) {
 if (partial > 16) return 1; int index = partial - 1; double lower_register_db = lerp(modal_radiation_db[0][index], modal_radiation_db[1][index], bass_to_middle); double treble_db = modal_radiation_db[2][index] + (index == 1 ? 6 * velocity : 0); return pow(10, lerp(lower_register_db, treble_db, middle_to_treble) / 20);
}

static void initialize_filters(void) {
 if (filters_ready) return;
 for (int index = 0; index < SOUND_FILTER_COUNT; index += 1) { double frequency = soundboard_specs[index][0], q = soundboard_specs[index][1], omega = TWO_PI * frequency / SAMPLE_RATE, alpha = sin(omega) / (2 * q), inverse_a0 = 1 / (1 + alpha); soundboard_filters[index][0] = alpha * inverse_a0; soundboard_filters[index][1] = 0; soundboard_filters[index][2] = -alpha * inverse_a0; soundboard_filters[index][3] = -2 * cos(omega) * inverse_a0; soundboard_filters[index][4] = (1 - alpha) * inverse_a0; soundboard_filters[index][9] = soundboard_specs[index][2]; }
 for (int index = 0; index < NOISE_FILTER_COUNT; index += 1) { double cutoff = noise_cutoffs[index], omega = TWO_PI * fabs(cutoff) / SAMPLE_RATE, cosine = cos(omega), alpha = sin(omega) / (2 * M_SQRT1_2), inverse_a0 = 1 / (1 + alpha), sign = cutoff < 0 ? 1 : -1, b0 = (1 + sign * cosine) * .5 * inverse_a0; noise_filters[index][0] = b0; noise_filters[index][1] = -(sign + cosine) * inverse_a0; noise_filters[index][2] = b0; noise_filters[index][3] = -2 * cosine * inverse_a0; noise_filters[index][4] = (1 - alpha) * inverse_a0; }
 filters_ready = 1;
}

__attribute__((export_name("calibration_ptr"))) uintptr_t calibration_ptr(void) { return (uintptr_t)calibration; }
__attribute__((export_name("output_ptr"))) uintptr_t output_ptr(void) { return (uintptr_t)output; }

static uint32_t seed_from_arguments(double frequency, double velocity) {
 union { double value; uint8_t bytes[8]; } f64 = {frequency}; union { float value; uint8_t bytes[4]; } f32 = {(float)velocity}; uint32_t hash = 0x811c9dc5; for (int index = 0; index < 8; index += 1) { hash ^= f64.bytes[index]; hash *= 0x01000193; } for (int index = 0; index < 4; index += 1) { hash ^= f32.bytes[index]; hash *= 0x01000193; } return hash;
}

static int hammer_force_length(double velocity, double reg, double frequency) {
 double soft_contact_seconds = lerp(.0034, .00085, reg), hard_contact_seconds = lerp(.00155, .00023, reg), unconstrained_contact = lerp(soft_contact_seconds, hard_contact_seconds, pow(velocity, .62)), treble_blend = transition((reg - .5) / .34), hard_contact_blend = transition((velocity - .08) / .52), tenor_cycle_limit = lerp(.24, .055, hard_contact_blend), cycle_limit = lerp(tenor_cycle_limit, .68, treble_blend), contact_seconds = fmin(unconstrained_contact, cycle_limit / frequency); return fmax(8, round(contact_seconds * SAMPLE_RATE));
}

static void create_hammer_force(int sample_count, double velocity, double reg) {
 double felt_exponent = lerp(1.35, 2.8, pow(velocity, .7)), rebound_skew = lerp(.18, -.08, velocity), integral = 0; for (int index = 0; index < sample_count; index += 1) { double position = (double)index / (sample_count - 1), compression = pow(sin(PI * position), felt_exponent), asymmetric_release = fmax(0, 1 + rebound_skew * (2 * position - 1)); state[FORCE_O + index] = compression * asymmetric_release; integral += state[FORCE_O + index]; } for (int index = 0; index < sample_count; index += 1) state[FORCE_O + index] /= integral;
}

static inline void init_string_mode(int index, int row, double pole, double step, double drive) { modes[row][index] = 0; modes[row + 1][index] = 0; modes[row + 2][index] = 2 * pole * cos(step); modes[row + 3][index] = -(pole * pole); modes[row + 4][index] = drive * sin(step); }
static inline double resonate_string(int index, int row, double force) { double result = modes[row + 2][index] * modes[row][index] + modes[row + 3][index] * modes[row + 1][index] + modes[row + 4][index] * force; modes[row + 1][index] = modes[row][index]; modes[row][index] = result; return result; }

static int create_string_modes(double frequency, double velocity, double midi, double reg) {
 double stiffness = interpolate_curve(midi, stiffness_curve, 26, 4), extreme_treble = clamp((reg - .88) / .12, 0, 1), bass_broadening = transition((reg - .12) / .32), treble_voicing = transition((reg - .5) / .34), upper_treble_coupling = transition((midi - 84) / 24), middle_broadening = bass_broadening * (1 - treble_voicing), bass_voicing = transition((48 - midi) / 27), middle_presence = bell(midi, 60, 10, 2), strike_position = lerp(.127, .112, reg), broad_hammer_cutoff = 2500 + 13000 * pow(velocity, 1.2) + 3000 * reg * reg, treble_hammer_cutoff = 1050 + 8900 * pow(velocity, 1.72) + 2000 * reg * reg, brightness_cutoff = lerp(treble_hammer_cutoff, broad_hammer_cutoff, middle_broadening), spectral_limit = fmin(SAMPLE_RATE * .475, 5500 + 15000 * pow(velocity, .62)), base_t60 = clamp(11 * pow(261.625565 / frequency, .45), 2.35, 31), stiffness_normalization = sqrt(1 + stiffness), width_cents = lerp(.32, 4.1, pow(clamp((midi - 31) / 77, 0, 1), 1.5)), upper_detune = lerp(.95, .7, transition((midi - 96) / 12)), unison_inequality = pow(reg, 1.5); int string_count = 1 + (midi >= 31) + (midi >= 49), mode_count = 0; double equal_weight = 1.0 / string_count;
 for (int partial = 1; partial <= 192; partial += 1) {
  double dispersed_frequency = partial * frequency * sqrt(1 + stiffness * partial * partial) / stiffness_normalization; if (dispersed_frequency > spectral_limit) break; int mobility_band = 0; while (mobility_band < 13 && dispersed_frequency >= mobility_band_edges[mobility_band]) mobility_band += 1;
  double strike_coupling = .2 + .8 * fabs(sin(PI * partial * strike_position)), felt_filter = bell(dispersed_frequency, 0, brightness_cutoff, 1.3), hammer_velocity_base = lerp(.78 + .12 * velocity, .9 + .04 * velocity, middle_broadening), velocity_brightening = pow(hammer_velocity_base, log2(partial)), radiation = .08 + .92 * dispersed_frequency / (dispersed_frequency + 150), mid_bridge_coupling = 1 + 2.1 * bell(midi, 65, 10, 2) * bell(partial, 2, .75, 2), treble_mode_damping = exp(-4.4 * pow(reg, 4.2) * (partial - 1) * (.72 - .32 * velocity - .22 * extreme_treble * velocity - 1.2 * upper_treble_coupling * (1 - velocity)) * lerp(1, .45, middle_broadening)), register_radiation_gain = 1 + 2.8 * pow(reg, 2.2), bridge_presence_shape = bell(log(dispersed_frequency / 1800), 0, .29, 2), bridge_presence_gain = 1 + .7 * middle_presence * bridge_presence_shape, bridge_antiresonance_shape = bell(log(dispersed_frequency / 790), 0, .08, 2), bridge_antiresonance = 1 - .85 * middle_presence * bridge_antiresonance_shape, middle_body_shape = bell(partial, 4.5, 1, 4), middle_body_level = 1 - .5 * middle_presence * middle_body_shape, bass_overtone_radiation = 1 + 4 * bass_voicing * (1 - exp(-(partial - 1) / 1.6)), weak_bass_fundamental = 1 - (.91 - .4 * bass_voicing) * bass_voicing * bell(partial, 1, .55, 4), weak_bass_second = 1 - (.93 - .4 * bass_voicing) * bass_voicing * bell(partial, 2, .55, 4), bass_high_partial_transition = transition((partial - 10) / 7.0), bass_high_partial_radiation = 1 + 4.5 * bass_voicing * bass_high_partial_transition, bass_presence_shape = bell(log(dispersed_frequency / 1800), 0, 1.05, 4), bass_presence_radiation = 1 + 4 * (1 - bass_broadening) * bass_presence_shape, partial_rolloff = fmax(.7, lerp(1.12, .58, middle_broadening) - .18 * bass_voicing);
  double modal_color = partial <= 12 ? calibration_value(calibration, 12, midi, velocity, partial - 1, .5, .476) : 0, mobility_color = calibration_value(calibration + 720, 14, midi, velocity, mobility_band, .5, .476), amplitude = strike_coupling * felt_filter * velocity_brightening * radiation * mid_bridge_coupling * treble_mode_damping * register_radiation_gain * bridge_presence_gain * bridge_antiresonance * middle_body_level * bass_overtone_radiation * weak_bass_fundamental * weak_bass_second * bass_high_partial_radiation * bass_presence_radiation * modal_radiation_gain(partial, bass_broadening, treble_voicing, velocity) * pow(10, -.94 * modal_color / 20) * pow(10, -.18 * mobility_color / 20) * pow(10, interpolate_curve(dispersed_frequency, bridge_curve_db, 16, 3) / 20) / pow(partial, partial_rolloff);
  double bass_presence_decay = transition(log2(dispersed_frequency / 500) / 2), undamped_partial_t60 = base_t60 * (.3 + .7 / pow(partial, .7)) / (1 + pow(dispersed_frequency / 9500, 2)) * (1 + .7 * (1 - bass_broadening) * bass_presence_decay), low_order_treble_tail = bell(partial, 1.5, 1, 4), treble_high_partial_tail = 1 - exp(-(partial - 1) / 2.5), middle_upper_mode_tail = bell(partial, 4.5, .9, 4), late_treble_tail = transition((midi - 94) / 14), uncorrected_slow_tail_t60 = undamped_partial_t60 * (1 + .15 * bass_voicing) * (1 + 1.5 * middle_presence * middle_upper_mode_tail) * exp(.5 * (.75 - velocity) * treble_high_partial_tail) * (1 - .8 * late_treble_tail * treble_high_partial_tail) * (1 - low_order_treble_tail * (.25 * treble_voicing + .2 * extreme_treble)), slow_tail_t60 = 60 / fmax(1, 60 / uncorrected_slow_tail_t60 + .45 * bridge_loss_db_per_second(midi, velocity, dispersed_frequency)), base_fast_fraction = .14 + .43 * (partial / (partial + 5.0)), middle_low_mode_loss = (.3 * middle_presence + .4 * bell(midi, 60, 1.5, 2) * transition((velocity - .8) / .17)) * bell(partial, 1.5, .8, 4), middle_body_sustain = .38 * middle_presence * middle_body_shape, maximum_fast_fraction = fmin(.99, (partial == 1 ? lerp(.965, .82, pow(reg, 1.5)) : lerp(.94, .68, pow(reg, 1.4))) + .16 * reg * (velocity - .5) + .6 * late_treble_tail * treble_high_partial_tail), fast_fraction = clamp(base_fast_fraction + 1.03 * reg * reg + middle_low_mode_loss - middle_body_sustain, 0, maximum_fast_fraction), fast_ratio = lerp(.21, .045, pow(reg, 1.35)) * lerp(1, .72, partial / (partial + 8.0)); if (partial == 2) fast_ratio *= lerp(1, .15, reg * reg);
  double fast_t60 = undamped_partial_t60 * fast_ratio, bridge_rise_seconds = (.00125 + .005 / (1 + partial * .42)) * lerp(1.35, .78, reg) * (1 + .9 * reg * reg + 3.5 * pow(reg, 6)) * (1 + .27 * bell(midi, 93, 10, 2) + .24 * extreme_treble), vertical_second_partial_boost = partial == 2 ? 1 + 4.5 * pow(reg, 3) * velocity : 1, damper_t60 = midi >= 96 ? .34 * (.75 + .25 / sqrt(partial)) : lerp(.16, .075, reg) / (1 + .055 * (partial - 1)), fast_pole = decay(6.907755, fast_t60), slow_pole = decay(6.907755, slow_tail_t60), polarization_t60 = slow_tail_t60 * lerp(.68, .34, reg), polarization_pole = decay(6.907755, polarization_t60), polarization_strength = (.035 + .11 * reg) * (.55 + .45 * velocity) / pow(partial, .2);
  for (int string_index = 0; string_index < string_count; string_index += 1) { double cents = string_count == 1 ? 0 : string_count == 2 ? (string_index == 0 ? -.47 : .53) * width_cents : (string_index == 0 ? -.83 : string_index == 1 ? -.34 : upper_detune) * width_cents, string_frequency = dispersed_frequency * pow(2, cents / 1200), angular_step = TWO_PI * string_frequency / SAMPLE_RATE, string_weight = lerp(equal_weight, string_count == 1 ? 1 : string_count == 2 ? (string_index == 0 ? .47 : .53) : (string_index == 0 ? .09 : string_index == 1 ? .46 : .45), unison_inequality), polarization_cents = (.35 + 1.1 * reg) * sin(2.17 * partial + 1.31 * string_index + .4), polarization_frequency = string_frequency * pow(2, polarization_cents / 1200), polarization_step = TWO_PI * polarization_frequency / SAMPLE_RATE, weighted_amplitude = amplitude * string_weight, fast_amplitude = weighted_amplitude * fast_fraction * vertical_second_partial_boost, slow_amplitude = weighted_amplitude * (1 - fast_fraction), polarization_amplitude = weighted_amplitude * polarization_strength; init_string_mode(mode_count, 0, fast_pole, angular_step, fast_amplitude); init_string_mode(mode_count, 5, slow_pole, angular_step, slow_amplitude); init_string_mode(mode_count, 10, polarization_pole, polarization_step, polarization_amplitude); mode_delays[0][mode_count] = string_count == 3 ? (string_index == 1 ? 2 : string_index == 2 ? 1 : 0) : 0; mode_delays[1][mode_count] = string_index + 1; modes[15][mode_count] = 0; modes[16][mode_count] = 1 - decay(1, bridge_rise_seconds); modes[17][mode_count] = 1; modes[18][mode_count] = decay(6.907755, damper_t60); mode_cutoff[mode_count] = decay_samples(fabs(weighted_amplitude) * fmax(fast_fraction * vertical_second_partial_boost, fmax(1 - fast_fraction, polarization_strength)), fmax(fast_pole, fmax(slow_pole, polarization_pole))); mode_count += 1; }
 }
 return mode_count;
}

static inline v128_t string_step(int row, int index) { v128_t y0 = wasm_v128_load(modes[row] + index), y1 = wasm_v128_load(modes[row + 1] + index), a1 = wasm_v128_load(modes[row + 2] + index), a2 = wasm_v128_load(modes[row + 3] + index), result = wasm_f64x2_add(wasm_f64x2_mul(a1, y0), wasm_f64x2_mul(a2, y1)); wasm_v128_store(modes[row + 1] + index, y0); wasm_v128_store(modes[row] + index, result); return result; }

static inline double filter_free_modes(int count, int released) {
 v128_t sum = wasm_f64x2_splat(0), one = wasm_f64x2_splat(1), two = wasm_f64x2_splat(2), three = wasm_f64x2_splat(3); int index = 0; for (; index + 1 < count; index += 2) { v128_t value = wasm_f64x2_add(wasm_f64x2_add(string_step(0, index), string_step(5, index)), string_step(10, index)), bridge = wasm_v128_load(modes[15] + index), bridge_step = wasm_v128_load(modes[16] + index); bridge = wasm_f64x2_add(bridge, wasm_f64x2_mul(wasm_f64x2_sub(one, bridge), bridge_step)); wasm_v128_store(modes[15] + index, bridge); v128_t transmission = wasm_f64x2_mul(wasm_f64x2_mul(bridge, bridge), wasm_f64x2_sub(three, wasm_f64x2_mul(two, bridge))), gain = wasm_v128_load(modes[17] + index); if (released) { gain = wasm_f64x2_mul(gain, wasm_v128_load(modes[18] + index)); wasm_v128_store(modes[17] + index, gain); } sum = wasm_f64x2_add(sum, wasm_f64x2_mul(wasm_f64x2_mul(value, transmission), gain)); } double lanes[2]; wasm_v128_store(lanes, sum); double result = lanes[0] + lanes[1]; if (index < count) { double fast = modes[2][index] * modes[0][index] + modes[3][index] * modes[1][index]; modes[1][index] = modes[0][index]; modes[0][index] = fast; double slow = modes[7][index] * modes[5][index] + modes[8][index] * modes[6][index]; modes[6][index] = modes[5][index]; modes[5][index] = slow; double polarization = modes[12][index] * modes[10][index] + modes[13][index] * modes[11][index]; modes[11][index] = modes[10][index]; modes[10][index] = polarization; modes[15][index] += (1 - modes[15][index]) * modes[16][index]; double bridge = modes[15][index], gain = modes[17][index]; if (released) { gain *= modes[18][index]; modes[17][index] = gain; } result += (fast + slow + polarization) * bridge * bridge * (3 - 2 * bridge) * gain; } return result;
}

static double filter_driven_strings(int mode_count, int strike_index, int hammer_samples, int released) {
 double strings = 0; for (int index = 0; index < mode_count; index += 1) { int force_index = strike_index - mode_delays[0][index], polarization_force_index = strike_index - mode_delays[1][index]; double string_force = force_index >= 0 && force_index < hammer_samples ? state[FORCE_O + force_index] : 0, polarization_force = polarization_force_index >= 0 && polarization_force_index < hammer_samples ? state[FORCE_O + polarization_force_index] : 0, fast = resonate_string(index, 0, string_force), slow = resonate_string(index, 5, string_force), polarization = resonate_string(index, 10, polarization_force); modes[15][index] += (1 - modes[15][index]) * modes[16][index]; if (released) modes[17][index] *= modes[18][index]; strings += (fast + slow + polarization) * smoothstep(modes[15][index]) * modes[17][index]; } return strings;
}

static inline void init_impact_mode(int index, int row, double pole, double step, double drive) { impact_state[row][index] = 0; impact_state[row + 1][index] = 0; impact_state[row + 2][index] = 2 * pole * cos(step); impact_state[row + 3][index] = -(pole * pole); impact_state[row + 4][index] = drive * sin(step); }

static void create_impact_soundboard(double velocity, double reg, double midi) {
 double impact_strength = pow(velocity, 1.15) * (.82 + .18 * reg), middle_body = bell(midi, 60, 10, 2), treble_body = transition((midi - 72) / 36), extreme_treble_body = transition((midi - 99) / 9), treble_velocity_voicing = transition((midi - 84) / 18), bass_plate_transition = transition((midi - 30) / 30), extreme_treble = clamp((reg - .88) / .12, 0, 1), body_velocity = fmax(velocity, .04), low_body_velocity_scale = lerp(pow(body_velocity, -.45), .1 * pow(body_velocity, -2.5), treble_velocity_voicing), coupled_body_drive = .75 * (1 + 2 * middle_body + 6 * extreme_treble_body) * low_body_velocity_scale; impact_body_count = treble_body > 0 ? 11 : 9; impact_attack_count = treble_body > 0 ? 11 : 0;
 for (int index = 0; index < IMPACT_COUNT; index += 1) { double frequency = impact_modes[index][0], decay_seconds = impact_modes[index][1], gain = impact_modes[index][2], angular_step = TWO_PI * frequency / SAMPLE_RATE, body_mode_weight = frequency < 1000 ? 1 : frequency < 1700 ? treble_body : 0; int low_body_mode = body_mode_weight > 0; double fast_decay_seconds = decay_seconds * (low_body_mode ? 1 + body_mode_weight * (1.75 * reg * reg + 13 * middle_body + 10 * treble_body) : 1), low_plate_weight = transition((400 - frequency) / 350), slow_body_fraction = low_body_mode ? body_mode_weight * (.2 * middle_body + .1 * treble_body * (1 + 2 * low_plate_weight)) : 0, slow_decay_seconds = decay_seconds * (1 + body_mode_weight * (90 * middle_body + 100 * treble_body)), fast_pole = decay(1, fast_decay_seconds), slow_pole = decay(1, slow_decay_seconds), attack_decay_multiplier = frequency >= 250 ? 2.8 : 2.2, attack_pole = decay(1, attack_decay_multiplier * decay_seconds), high_frequency = fmax(1, frequency / 500), felt_brightness = pow(.58 + .42 * velocity, log2(high_frequency)), mode_shape = .72 + .28 * sin(.73 * index + 3.1 * reg), impact_radiation = lerp(1, clamp(sqrt(frequency / 2000), .2, 1), reg * reg); if (low_body_mode) impact_radiation = lerp(impact_radiation, 1, extreme_treble); double mid_plate_scale = frequency >= 1800 && frequency < 3800 ? lerp(1, .18, extreme_treble) : 1, low_body_drive = lerp(1, coupled_body_drive, body_mode_weight), bass_high_plate_scale = frequency >= 1800 ? lerp(.1, 1, bass_plate_transition) : 1; int color_band = frequency < 250 ? 0 : frequency < 1000 ? 1 : frequency < 2500 ? 2 : 3; double drive = gain * low_body_drive * bass_high_plate_scale * mid_plate_scale * impact_strength * felt_brightness * mode_shape * impact_radiation * pow(10, -1.08 * calibration_value(calibration + 540, 4, midi, velocity, color_band, .5, .476) / 20); init_impact_mode(index, 0, fast_pole, angular_step, drive * (1 - slow_body_fraction)); init_impact_mode(index, 5, slow_pole, angular_step, drive * slow_body_fraction); init_impact_mode(index, 10, attack_pole, angular_step, drive * (2.5 * body_mode_weight * treble_body)); impact_state[15][index] = 0; impact_state[16][index] = 1 - decay(1, .005); }
}

static inline v128_t impact_step(int row, int index, v128_t force) { v128_t y0 = wasm_v128_load(impact_state[row] + index), y1 = wasm_v128_load(impact_state[row + 1] + index), a1 = wasm_v128_load(impact_state[row + 2] + index), a2 = wasm_v128_load(impact_state[row + 3] + index), drive = wasm_v128_load(impact_state[row + 4] + index), result = wasm_f64x2_add(wasm_f64x2_add(wasm_f64x2_mul(a1, y0), wasm_f64x2_mul(a2, y1)), wasm_f64x2_mul(drive, force)); wasm_v128_store(impact_state[row + 1] + index, y0); wasm_v128_store(impact_state[row] + index, result); return result; }
static inline double impact_scalar(int row, int index, double force) { double result = impact_state[row + 2][index] * impact_state[row][index] + impact_state[row + 3][index] * impact_state[row + 1][index] + impact_state[row + 4][index] * force; impact_state[row + 1][index] = impact_state[row][index]; impact_state[row][index] = result; return result; }

static double filter_impact_soundboard(double scalar_force) {
 v128_t sum = wasm_f64x2_splat(0), force = wasm_f64x2_splat(scalar_force), one = wasm_f64x2_splat(1); int index = 0; for (; index + 1 < impact_attack_count; index += 2) { v128_t fast = impact_step(0, index, force), slow = impact_step(5, index, force), attack = impact_step(10, index, force), envelope = wasm_v128_load(impact_state[15] + index); envelope = wasm_f64x2_add(envelope, wasm_f64x2_mul(wasm_f64x2_sub(one, envelope), wasm_v128_load(impact_state[16] + index))); wasm_v128_store(impact_state[15] + index, envelope); sum = wasm_f64x2_add(sum, wasm_f64x2_add(wasm_f64x2_add(fast, slow), wasm_f64x2_mul(attack, envelope))); } if (index < impact_attack_count) { double fast = impact_scalar(0, index, scalar_force), slow = impact_scalar(5, index, scalar_force), attack = impact_scalar(10, index, scalar_force); impact_state[15][index] += (1 - impact_state[15][index]) * impact_state[16][index]; double value = fast + slow + attack * impact_state[15][index]; sum = wasm_f64x2_add(sum, wasm_f64x2_make(value, 0)); index += 1; } for (; index + 1 < impact_body_count; index += 2) sum = wasm_f64x2_add(sum, wasm_f64x2_add(impact_step(0, index, force), impact_step(5, index, force))); if (index < impact_body_count) { double value = impact_scalar(0, index, scalar_force) + impact_scalar(5, index, scalar_force); sum = wasm_f64x2_add(sum, wasm_f64x2_make(value, 0)); index += 1; } for (; index + 1 < IMPACT_COUNT; index += 2) sum = wasm_f64x2_add(sum, impact_step(0, index, force)); if (index < IMPACT_COUNT) sum = wasm_f64x2_add(sum, wasm_f64x2_make(impact_scalar(0, index, scalar_force), 0)); double lanes[2]; wasm_v128_store(lanes, sum); return lanes[0] + lanes[1];
}

static inline double filter_biquad(double input, const double *filter, int offset) { double result = filter[0] * input + filter[1] * state[offset] + filter[2] * state[offset + 1] - filter[3] * state[offset + 2] - filter[4] * state[offset + 3]; state[offset + 1] = state[offset]; state[offset] = input; state[offset + 3] = state[offset + 2]; state[offset + 2] = result; return result; }
static double filter_chain(double input, double filters[][9], int state_offset, int start, int end) { while (start < end) { input = filter_biquad(input, filters[start], state_offset + start * 4); start += 1; } return input; }
static double filter_soundboard(double input) { double result = 0; for (int index = 0; index < SOUND_FILTER_COUNT; index += 1) result += soundboard_filters[index][9] * filter_biquad(input, soundboard_filters[index], SOUND_O + index * 4); return result; }

static void radiation_response(double step, double omega, int offset) { double pole = 1 - step, real = 1 - pole * cos(omega), imaginary = pole * sin(omega), scale = step / (real * real + imaginary * imaginary); state[offset] = scale * real; state[offset + 1] = -scale * imaginary; }
static double radiation_normalization(double frequency, double low_step, double center_step, double high_step, double low_gain, double center_gain, double high_gain) { double omega = TWO_PI * frequency / SAMPLE_RATE; radiation_response(low_step, omega, RAD_O); radiation_response(center_step, omega, RAD_O + 2); radiation_response(high_step, omega, RAD_O + 4); double real = high_gain + (low_gain - center_gain) * state[RAD_O] + (center_gain - 1) * state[RAD_O + 2] + (1 - high_gain) * state[RAD_O + 4], imaginary = (low_gain - center_gain) * state[RAD_O + 1] + (center_gain - 1) * state[RAD_O + 3] + (1 - high_gain) * state[RAD_O + 5]; return hypot(real, imaginary); }

__attribute__((export_name("synthesize"))) int synthesize(double note_hz, double velocity, double duration_seconds) {
 initialize_filters(); double frequency = clamp(note_hz, 27.5, 4186.009044809578), strike_velocity = clamp(velocity, 0, 1), duration = clamp(duration_seconds, 0, 30); int sample_count = round(duration * SAMPLE_RATE); if (sample_count == 0) return 0; if (strike_velocity == 0) { memset(output, 0, sample_count * sizeof(float)); return sample_count; }
 double midi = 69 + 12 * log2(frequency / 440), reg = clamp((midi - 21) / 87, 0, 1); int hammer_samples = hammer_force_length(strike_velocity, reg, frequency); memset(state + SOUND_O, 0, (BOARD_O - SOUND_O) * sizeof(double)); create_hammer_force(hammer_samples, strike_velocity, reg); int mode_count = create_string_modes(frequency, strike_velocity, midi, reg), active_mode_count = mode_count; create_impact_soundboard(strike_velocity, reg, midi); uint32_t noise_seed = seed_from_arguments(frequency, strike_velocity), noise_state = noise_seed ? noise_seed : 0x6d2b79f5, body_noise_state = (noise_seed ^ 0x9e3779b9) ? (noise_seed ^ 0x9e3779b9) : 0x6d2b79f5;
 double release_seconds = clamp(.145 * pow(110 / frequency, .14), .052, .185); int release_samples = fmin(sample_count, fmax(1, round(release_seconds * SAMPLE_RATE))), release_start = sample_count - release_samples, start_fade_samples = round(lerp(160, 32, transition((midi - 21) / 9))), final_fade_samples = fmin(sample_count, 256); double top_velocity_transition = transition((midi - 99) / 9), upper_action_leverage = bell(midi, 105, 2.2, 2), velocity_exponent = .28 + reg + .64 * top_velocity_transition + .45 * upper_action_leverage + .82 * transition((36 - midi) / 15), bass_velocity_voicing = transition((48 - midi) / 27), bass_velocity_bump_db = 7 * bass_velocity_voicing * bell(strike_velocity, .38, .25, 2), bass_compensation = 1 + .48 * clamp((45 - midi) / 24, 0, 1), bass_trim = lerp(.25, 1, transition((midi - 21) / 27)), velocity_gain = .3 * bass_compensation * bass_trim * pow(10, interpolate_curve(midi, radiation_curve_db, 30, 2) / 20) * pow(10, bass_velocity_bump_db / 20) * pow(strike_velocity, velocity_exponent) * (.84 + .16 * strike_velocity);
 double hammer_cutoff = 1300 + 8600 * pow(strike_velocity, 1.55), hammer_lowpass_step = 1 - exp(-TWO_PI * hammer_cutoff / SAMPLE_RATE), hammer_lowpass = 0, mechanical_lowpass = 0, damper_lowpass = 0, mechanical_lowpass_step = 1 - exp(-TWO_PI * 950 / SAMPLE_RATE), damper_lowpass_step = 1 - exp(-TWO_PI * 1150 / SAMPLE_RATE); int hammer_noise_samples = fmin(sample_count, round(.085 * SAMPLE_RATE)); double bass_noise_transition = transition((midi - 36) / 24), felt_presence_radiation = lerp(.12, 1, bass_noise_transition), felt_air_radiation = lerp(.04, 1, bass_noise_transition); int strike_delay_samples = 8; double thump_frequency = lerp(82, 155, reg) * lerp(.96, 1.08, strike_velocity), diffuse_body_decay_seconds = lerp(2.6, 1.15, reg), body_rise_pole = decay(1, .004), body_tail_pole = decay(1, diffuse_body_decay_seconds), plate_rise_pole = decay(1, .06), plate_tail_pole = decay(1, .45), felt_rise_pole = decay(1, .00055), felt_tail_pole = decay(1, .028), presence_rise_pole = decay(1, .00035), presence_tail_pole = decay(1, .07), early_rise_pole = decay(1, .0012), early_tail_pole = decay(1, .008), body_grain_tail_pole = decay(1, .032), thump_tail_pole = decay(1, .012), thump_rise_pole = decay(1, .00045), damper_rise_pole = decay(1, .0015), damper_tail_pole = decay(1, .026), diffuse_plate_register = clamp((midi - 57) / 36, 0, 1), upper_bridge_plate = 1 + 2 * bell(midi, 81, 10, 2), top_body_transition = transition((midi - 93) / 12), diffuse_low_body_scale = 1 - .97 * top_body_transition * sqrt(strike_velocity);
 double radiation_low_gain = pow(10, 1.35 * radiation_eq_db(midi, strike_velocity, 0) / 20), radiation_center_gain = pow(10, .75 * radiation_eq_db(midi, strike_velocity, 1) / 20), radiation_high_gain = pow(10, 1.35 * radiation_eq_db(midi, strike_velocity, 2) / 20), radiation_low_step = 1 - exp(-TWO_PI * 250 / SAMPLE_RATE), radiation_center_step = 1 - exp(-TWO_PI * 900 / SAMPLE_RATE), radiation_high_step = 1 - exp(-TWO_PI * 2500 / SAMPLE_RATE), radiation_gain_normalization = radiation_normalization(frequency, radiation_low_step, radiation_center_step, radiation_high_step, radiation_low_gain, radiation_center_gain, radiation_high_gain), radiation_low = 0, radiation_center = 0, radiation_mid = 0, board_loss_scale = -.48 * M_LN10 / (20 * SAMPLE_RATE); for (int band = 0; band < 4; band += 1) { state[BOARD_O + band] = exp(board_loss_scale * board_loss_db_per_second(midi, strike_velocity, band)); state[BOARD_O + 4 + band] = 1; }
 double string_mix = .74 + .13 * bell(midi, 93, 10, 2), previous_input = 0, dc_blocker = 0, body_rise_value = 1, body_tail_value = 1, plate_rise_value = 1, plate_tail_value = 1, felt_rise_value = 1, felt_tail_value = 1, presence_rise_value = 1, presence_tail_value = 1, early_rise_value = 1, early_tail_value = 1, body_grain_tail_value = 1, thump_tail_value = 1, thump_rise_value = 1, damper_rise_value = 1, damper_tail_value = 1, dc_pole = .99945;
 for (int sample_index = 0; sample_index < sample_count; sample_index += 1) {
  int strike_index = sample_index - strike_delay_samples, released = sample_index >= release_start; double force = strike_index >= 0 && strike_index < hammer_samples ? state[FORCE_O + strike_index] : 0, diffuse_body = 0;
  if (strike_index >= 0) { body_noise_state ^= body_noise_state << 13; body_noise_state ^= body_noise_state >> 17; body_noise_state ^= body_noise_state << 5; double body_white = (double)body_noise_state / 4294967296.0 * 2 - 1, body_grain = filter_chain(body_white, noise_filters, NOISE_O, 9, 12), plate_grain = filter_chain(body_white, noise_filters, NOISE_O, 12, 14), body_rise = 1 - body_rise_value, body_tail = body_tail_value, plate_rise = 1 - plate_rise_value, plate_tail = plate_tail_value; diffuse_body = .015 * (1.7 - 1.4 * strike_velocity) * (.55 + .45 * reg) * diffuse_low_body_scale * body_grain * body_rise * body_tail + .002 * diffuse_plate_register * upper_bridge_plate * plate_grain * plate_rise * plate_tail; }
  while (active_mode_count > 0 && strike_index >= 0 && (uint32_t)strike_index >= mode_cutoff[active_mode_count - 1]) active_mode_count -= 1; double strings = strike_index < hammer_samples + 3 ? filter_driven_strings(active_mode_count, strike_index, hammer_samples, released) : filter_free_modes(active_mode_count, released), hammer = 0;
  if (strike_index >= 0 && strike_index < hammer_noise_samples) { noise_state ^= noise_state << 13; noise_state ^= noise_state >> 17; noise_state ^= noise_state << 5; double white = (double)noise_state / 4294967296.0 * 2 - 1; hammer_lowpass += hammer_lowpass_step * (white - hammer_lowpass); double felt_lowpassed = filter_chain(white, noise_filters, NOISE_O, 0, 3), felt_presence = filter_biquad(felt_lowpassed, noise_filters[3], NOISE_O + 12), felt_air = filter_chain(white, noise_filters, NOISE_O, 4, 6), body_grain = filter_chain(white, noise_filters, NOISE_O, 6, 9); mechanical_lowpass += mechanical_lowpass_step * (white - mechanical_lowpass); double lingering_felt = felt_lowpassed * (1 - felt_rise_value) * felt_tail_value, lingering_presence = felt_presence * (1 - presence_rise_value) * presence_tail_value, early_presence = felt_presence * (1 - early_rise_value) * early_tail_value, lingering_air = felt_air * (1 - presence_rise_value) * presence_tail_value, body_grain_envelope = (1 - body_rise_value) * body_grain_tail_value; hammer = .024 * pow(strike_velocity, 1.55) * lingering_felt + .05 * pow(strike_velocity, 1.75) * felt_presence_radiation * lingering_presence + .04 * pow(strike_velocity, 1.62) * felt_presence_radiation * early_presence + .0022 * pow(strike_velocity, 1.9) * felt_air_radiation * lingering_air + .2 * pow(strike_velocity, .45) * reg * reg * body_grain * body_grain_envelope; if (strike_index < hammer_samples) { double collision_shape = state[FORCE_O + strike_index] * hammer_samples, collision = sqrt(collision_shape), felt = hammer_lowpass * collision, felt_contact = felt_presence * collision, air_contact = felt_air * collision, mechanical_impact = .03 * pow(strike_velocity, 1.2) * mechanical_lowpass * collision, thump = sin(TWO_PI * thump_frequency * strike_index / SAMPLE_RATE) * thump_tail_value * (1 - thump_rise_value); hammer += (.005 * pow(strike_velocity, 1.35) * felt + .012 * pow(strike_velocity, 1.55) * felt_presence_radiation * felt_contact + .006 * pow(strike_velocity, 1.9) * felt_air_radiation * air_contact + mechanical_impact + .006 * thump) * (.72 + .28 * reg); } }
  double damper = 0; if (released && release_start > 0 && midi < 100) { int release_index = sample_index - release_start; double release_position = (double)release_index / release_samples; noise_state ^= noise_state << 13; noise_state ^= noise_state >> 17; noise_state ^= noise_state << 5; double white = (double)noise_state / 4294967296.0 * 2 - 1; damper_lowpass += damper_lowpass_step * (white - damper_lowpass); double noise_envelope = (1 - damper_rise_value) * damper_tail_value * sin(PI * release_position); damper = .011 * (.35 + .65 * strike_velocity) * damper_lowpass * noise_envelope; damper_rise_value *= damper_rise_pole; damper_tail_value *= damper_tail_pole; }
  hammer += diffuse_body; double excitation = strings + hammer, body = filter_soundboard(excitation), impact_body = filter_impact_soundboard(force), sample = velocity_gain * (string_mix * strings + 1.18 * body + 1.35 * impact_body + hammer + damper); radiation_low += radiation_low_step * (sample - radiation_low); radiation_center += radiation_center_step * (sample - radiation_center); radiation_mid += radiation_high_step * (sample - radiation_mid); for (int band = 0; band < 4; band += 1) state[BOARD_O + 4 + band] = fmin(4, fmax(.1, state[BOARD_O + 4 + band] * state[BOARD_O + band])); sample = (state[BOARD_O + 4] * radiation_low_gain * radiation_low + state[BOARD_O + 5] * radiation_center_gain * (radiation_center - radiation_low) + state[BOARD_O + 6] * (radiation_mid - radiation_center) + state[BOARD_O + 7] * radiation_high_gain * (sample - radiation_mid)) / radiation_gain_normalization; sample = .94 * tanh(1.12 * sample); double highpassed = sample - previous_input + dc_pole * dc_blocker; previous_input = sample; dc_blocker = highpassed; sample = highpassed;
  if (sample_index < start_fade_samples) { double start_fade = .5 - .5 * cos(PI * sample_index / (start_fade_samples - 1)); sample *= start_fade * start_fade; } if (sample_index >= sample_count - final_fade_samples) { int remaining = sample_count - 1 - sample_index; double end_fade = .5 - .5 * cos(PI * remaining / (final_fade_samples - 1 ? final_fade_samples - 1 : 1)); sample *= end_fade; } output[sample_index] = fmin(.94, fmax(-.94, sample));
  if (strike_index >= 0) { body_rise_value *= body_rise_pole; body_tail_value *= body_tail_pole; plate_rise_value *= plate_rise_pole; plate_tail_value *= plate_tail_pole; } if (strike_index >= 0 && strike_index < hammer_noise_samples) { felt_rise_value *= felt_rise_pole; felt_tail_value *= felt_tail_pole; presence_rise_value *= presence_rise_pole; presence_tail_value *= presence_tail_pole; early_rise_value *= early_rise_pole; early_tail_value *= early_tail_pole; body_grain_tail_value *= body_grain_tail_pole; thump_tail_value *= thump_tail_pole; thump_rise_value *= thump_rise_pole; }
 }
 output[0] = 0; output[sample_count - 1] = 0; return sample_count;
}
